const MEETUP = {
    LOAD: "REQUEST_DATA",
    LOAD_SUCCESS: "RECEIVE_DATA",
    SAVE_MEETUP: "SAVE_MEETUP",
    GET_FAVORITE: "GET_FAVORITE",
    ADD_FAVORITE: "ADD_FAVORITE",
    REMOVE_FAVORITE: "REMOVE_FAVORITE",
};

export default MEETUP;